### ISSUE TITLE
How can i run this in windows operating system

### ISSUE THREAD

**Issue by johura** [rafael859/pam_duress#13]
My master's thesis topic is as same as your title. That's why I tried to run many times in windows but it failed to get so many errors. Please help me to suggest some points to run the code.

**Comment by Lqp1** [comment]
This code is a PAM Module (see [wikipedia PAM](https://en.wikipedia.org/wiki/Pluggable_authentication_module); PAM is a Unix framework and is not available on Windows.
So basically you need to change all PAM related calls in this repository to Windows' own authentication framework. You can start reading [this](https://docs.microsoft.com/en-us/windows/win32/secauthn/credential-providers-in-windows) documentation about Windows credentials.

Also atm all the scripts in this repo rely on Linux/BSD file hierarchy so you'll need to change that also.
