### ISSUE TITLE
OpenSSL 1.1 types made opaqu

### ISSUE THREAD

**Issue by schongallam** [rafael859/pam_duress#9]
Hello everyone,
I'm pretty new to github so apologies if this is inappropriate.  Let me know and I'll remove it.

OpenSSL 1.1 made many types opaque and pam_duress will not compile with that version.  I forked it and, time permitting, will chip away at this issue

**Comment by Lqp1** [comment]
I also encountered this issue. I did not find any fix in your fork of this repo.

Any chance you can provide a PR with the fixes ?

If you're not working anymore on it I can do it as well (I made it run successfully on Debian buster)

Br

**Comment by Lqp1** [comment]
@schongallam you can check my PR if interested.
